### ISSUE TITLE
Dockerfile ${VERSION} is not being populated

### ISSUE THREAD

**Issue by kbrownlees** [shm-open/code-push-server#148]
It does not look like the VERSION is being populated correctly when doing the docker build. I believe is is working because `npm install package@`just installs the latest version available.

**Comment by rocwind** [comment]
Good catch!
Didn't realize variables defined in Makefile are not environment variables, trying to set it by:
https://github.com/shm-open/code-push-server/commit/c93a4acdf14bd2bd4a4c7524c053321676ac4715

**Comment by kbrownlees** [comment]
@rocwind I believe you need to use something along the lines of https://github.com/cloudscapelabs/code-push-server/commit/70483ae9d59e5a1fdf4b87d48115ffffc033fb3a (with --build-var). Bit swamped at the moment so can't make a PR I am afraid.

**Comment by rocwind** [comment]
@kbrownlees Thanks for the example! I'll have a try

**Comment by rocwind** [comment]
It should be addressed by https://github.com/shm-open/code-push-server/commit/0619e4ec399714095f9b30a136b1808c7642a04e, closing this issue.
