### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by chenweigh** [shm-open/code-push-server#196]
关于code-push-server 使用问题，可以使用appcenter-cli客户端吗？我看目前是code-push-cli才行。我要怎么替换成appcenter-cli

**Comment by rocwind** [comment]
应该不能换成appcenter-cli.
appcenter-cli是与ms官方的服务一起工作的, 它不能定制登录的方式 (服务器地址), 所以我们才会维护一份code-push-cli fork用在这个开源的服务上

**Comment by chenweigh** [comment]
好的，感谢。那我按照咱们的开源代码改一下。
