### ISSUE TITLE
请问兼容到哪个版本的react-native-code-push?

### ISSUE THREAD

**Issue by chj-damon** [shm-open/code-push-server#231]
我在项目里面使用的是react-native-code-push@7.0.5，然后本地调试的时候配置的地址是http://127.0.0.1:3000

准备工作我已经都做好了，app也能正常跑起来。热更新的patch包也已经成功创建，我在数据库里面也能看到。但是在打开app的时候没有任何效果。也不知道到底请求了没有，也没有报错。

像这种情况我应该怎么排查可能是哪里的问题呢？包版本太高了？还是什么别的问题？

请大佬指教一下。万分感谢！

**Comment by chj-damon** [comment]
我看了一下，codePush.sync方法执行后会请求到server的/v0.1/public/codepush/update_check，然后就没有后续了。

为什么最新的7.0.5版本的包请求的会是这个/v0.1的，什么情况下会请求/updateCheck这个呢？

**Comment by rocwind** [comment]
Hi @chj-damon ,
查了一下我们之前在用的是react-native-code-push@7.0.2, 7.0.5只是补丁版本更新, 理论上应该不会有不兼容的情况. 我自己有大半年没有做RN相关的开发了, 只能试着提供一些信息看看有没有帮助.

1. /v0.1 的API路径没有问题, 它很奇怪, 但它是MS官方从code-push服务往app center迁移的时候选择的;
2. update_check和updateCheck分别可能对应了这个迁移前后的新旧版本sdk, 新的理论上都走/v0.1的 (code-push-cli用的是旧版API来上传包的);
3. code push客户端在(根据配置的策略)检查更新的时候会请求这个update_check, 通过拿到的hash/版本信息来判断有没有更新以进行下一步. 一般的过程是: update_check -> 有更新并且拿到下载地址 -> 客户端下载解压, 校验签名 -> 客户端应用code push补丁/重启生效.
4. 常遇到的code push没有成功的情况可能有: 客户端是debug build(debug build因为有dev server, 默认的配置是不会应用code push的版本的); 客户端下载完以后校验签名/hash失败; code push的代码本身有问题启动不了客户端回滚了.
5. 调试的时候可以关注一下update_check的返回值, 如果正常下发了更新的版本则查客户端的日志 - debug版本虽然不加载code push的包, 但是可以跟到code push sdk的原生代码里调试下载/校验的代码, 看看哪步出了问题; 如果回复是没有更新的话, 可以看看服务端的日志有没有线索

**Comment by chj-damon** [comment]
已经解决了，原来是我手机无法跟我本地电脑部署的服务进行通信，加上代理后没问题了。说明功能和配置是哪有什么问题的，这样我只需要在线上部署这个服务器暴露一个公网地址应该就可以正常使用了。非常感谢作者！！
