### ISSUE TITLE
yml文件里需要修改的地方有哪些？

### ISSUE THREAD

**Issue by chj-damon** [shm-open/code-push-server#232]
https://github.com/shm-open/code-push-server/blob/master/docs/install-server-by-docker.cn.md

我看这个文档里面写的修改配置的地方就列出了两个，一个是download_url，一个是jwt.tokenSecret
那请问mysql和redis这两个地方的配置不需要修改吗？

**Comment by rocwind** [comment]
mysql和redis的实例是在[docker-compose.yml](https://github.com/shm-open/code-push-server/blob/master/docker-compose.yml)里配置好的, 可以不修改.

**Comment by chj-damon** [comment]
谢谢！确实是可以的！
