### ISSUE TITLE
在RN最新版本0.73中如何配置CodePush

### ISSUE THREAD

**Issue by sHenGlinL** [shm-open/code-push-server#241]
在RN最新版本0.73中，没有了MainApplication.java文件，在MainApplication.kt如何配置CodePush?

`override fun getPackages(): List<ReactPackage> = PackageList(this).packages.apply {
          add(CodePush(
            getResources().getString(R.string.CodePushDeploymentKey), 
            getApplicationContext(),
            BuildConfig.DEBUG, 
            getResources().getString(R.string.CodePushServerURL)
          ))
 }`
 这样配置会报错
 
<img width="319" alt="image" src="https://github.com/shm-open/code-push-server/assets/41774732/1551720d-3d7f-4330-abf4-ba8454d2204b">

**Comment by sHenGlinL** [comment]
<img width="647" alt="image" src="https://github.com/shm-open/code-push-server/assets/41774732/98f49966-6474-4f7a-89bf-e3809736565b">

**Comment by billxie1988** [comment]
在React Native 0.73及更高版本中，如果转向使用Kotlin来替代Java用作Android开发语言，配置CodePush的方式与Java类似，只是语法上会有些许不同。使用Kotlin语言

```
import com.microsoft.codepush.react.CodePush
import com.facebook.react.ReactApplication
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.shell.MainReactPackage
import com.facebook.soloader.SoLoader
class MainApplication : Application(), ReactApplication {

    private val reactNativeHost: ReactNativeHost = object : ReactNativeHost(this) {
        override fun getJSBundleFile(): String? {
            return CodePush.getJSBundleFile()
        }
        
        override fun getPackages(): List<ReactPackage> {
            return PackageList(this).packages.apply {
                add(CodePush(resources.getString(R.string.reactNativeCodePush_androidDeploymentKey), applicationContext, BuildConfig.DEBUG))
            }
        }
        
        override fun getUseDeveloperSupport(): Boolean {
            return BuildConfig.DEBUG
        }
        
        override fun getJSMainModuleName(): String {
            return "index"
        }
    }

    override fun getReactNativeHost(): ReactNativeHost {
        return reactNativeHost
    }

    override fun onCreate() {
        super.onCreate()
        SoLoader.init(this, /* native exopackage */ false)
        initializeFlipper(this, reactNativeHost.reactInstanceManager)
    }
}

```

**Comment by littleseven007** [comment]
临时方案：去掉上述手动添加的‘ add(CodePush(xxx))代码，将react-native-code-push中源码CodePush.java中的mServerUrl替换为自己的服务端地址

**Comment by sHenGlinL** [comment]
> 临时方案：去掉上述手动添加的‘ add(CodePush(xxx))代码，将react-native-code-push中源码CodePush.java中的mServerUrl替换为自己的服务端地址

去掉“add(CodePush(xxx))”就可以了
