### ISSUE TITLE
Initial registration

### ISSUE THREAD

**Issue by byronigoe** [shm-open/code-push-server#81]
1. When I run `code-push register http://localhost:3000` my browser opens the login page, but I think it's supposed to open the register page.
2. Both auth/login and auth/register have no `action` defined on their forms, and thus the JavaScript code doesn't POST the data anywhere.
3. I added /users/registerCode as the action to the register form, but it does not return the token that is expected.

I am happy to help complete the implementation of this, but I don't want to duplicate efforts if you've already done it, and I want to make sure I'm doing the right thing. Thanks.

**Comment by rocwind** [comment]
#82 has been merged and new version released
